FROM php:8.1.2-fpm

# install するパッケージを最新に
RUN apt-get update \
 # 必要最小限のパッケージを入れる
 && apt-get install -y --no-install-recommends \
    libzip-dev \
 # 拡張パッケージのインストール
 && docker-php-ext-install zip \
 # 掃除
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*

# composer install
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer